feat: add more features and solve some bugs on pagination component
rocketseat-education/react-na-pratica-01 pull request #3
Opened 2024-02-22 18:07 UTC by maik-emanoel

Some features I did:

Make the select work;
Solve bugs when the user was gonna to the last page and changed the select value;
Let all the info dynamic;

It's my first time make I PR, so I'm sorry some mistake.

2024-02-22 23:48 UTC, filipedev6 requested changes

2024-02-22 23:48 UTC, filipedev6 commented on src/app.tsx
> +          )}
```suggestion
          <Pagination 
            pages={tagsResponse.pages} 
            items={tagsResponse.items} 
            page={page} 
            itemsPerPage={per_page}/>
          )}
```

2024-02-22 23:48 UTC, filipedev6 commented on src/components/pagination.tsx
> +  itemsPerPage: Tag[]
```suggestion
  itemsPerPage: number
```

2024-02-22 23:48 UTC, filipedev6 commented on src/components/pagination.tsx
> +  : 10;
```suggestion
```

Criando um código que já foi criado no componente pai, não existe necessidade.

2024-02-22 23:48 UTC, filipedev6 commented on src/components/pagination.tsx
> +      <span>Showing {itemsPerPage.length} of {items} items</span>
```suggestion
      <span>Showing {itemsPerPage} of {items} items</span>
```

2024-02-22 23:48 UTC, filipedev6 commented on src/components/pagination.tsx
> +          <Select defaultValue={String(rowsPerPage)} onValueChange={handleNumberOfRows}>
```suggestion
          <Select defaultValue={String(itemsPerPage)} onValueChange={handleNumberOfRows}>
```

2024-02-22 23:59 UTC, filipedev6 commented
Contribute some changes to your project, don't get me wrong but there are some important points that make a difference. Nice to meet you, I hope you are happy with my contributions!

Att: https://www.linkedin.com/in/eulerfilipe

2024-02-23 12:27 UTC, maik-emanoel reviewed
Good changes

2024-02-23 20:27 UTC, filipedev6 commented
@diego3g approve this PR 🚀

2024-04-01 18:30 UTC, closed without merging